# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

empb_beta_binomial_c_loop <- function(G, Sg, Tg, Ng, eta, tol, maxIter, method) {
    .Call('_DHBayes_empb_beta_binomial_c_loop', PACKAGE = 'DHBayes', G, Sg, Tg, Ng, eta, tol, maxIter, method)
}

